"""add created_at column to movie_ratings table

Revision ID: ae351b33de02
Revises: 6cca6ba695f2
Create Date: 2026-01-03 19:43:33.105655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae351b33de02'
down_revision: Union[str, Sequence[str], None] = '6cca6ba695f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie_ratings', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie_ratings', 'created_at')
    # ### end Alembic commands ###
